### ISSUE TITLE
how to build libdedrop.dll

### ISSUE THREAD

**Issue by zhonghh13** [kholia/dedrop#3]
could you show me how to build the libdedrop.dll? i want to dedrop the Dropbox on windows, but i am not familiar with how to do that.

**Comment by kholia** [comment]
`libdedrop.dll` is meant to be used on Linux.

**Comment by zhonghh13** [comment]
what should i do on windows?

**Comment by kholia** [comment]
See https://github.com/stephenfewer/ReflectiveDLLInjection

Please remember that we cannot provide any end-user support. You are on your own, good luck!
